version: 1.0.{build}

image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

assembly_info:
  patch: true
  file: 'src\Properties\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

configuration:
- Release

platform: Any CPU

# scripts to run before build
before_build:
- nuget restore -verbosity quiet

build:
 project: DesignPatternsKata.sln
 verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"vstest.console.exe" -targetargs:""C:\projects\designpatternskata\src\DesignPatternsKataTests\bin\Release\DesignPatternsKataTests.dll" /InIsolation /logger:Appveyor" -filter:"-[*Tests*]*" -output:".\designpatternskata_coverage.xml" -excludebyattribute:*.ExcludeFromCodeCoverage* -returntargetcode
