version: 1.0.{build}

image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

assembly_info:
  patch: true
  file: 'src\Properties\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

configuration:
- Release

platform: Any CPU

# scripts to run before build
before_build:
- nuget restore -verbosity quiet

build:
 project: DesignPatternsKata.sln
 verbosity: minimal